export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  MENU: "/menu",
  ORDER: "/order",
  ORDER_CHECKOUT: "/order/checkout",
  ORDER_COMPLETE: "/order/complete",
  BOARD: "/board",
  MY: "/my",
  MY_ORDERS: "/my/orders",
  MY_PROFILE: "/my/profile",
  ADMIN: "/admin",
  ADMIN_MEMBERS: "/admin/members",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_INVENTORY: "/admin/inventory",
  ADMIN_SALES: "/admin/sales",
  ADMIN_NOTIFICATIONS: "/admin/notifications",
  ADMIN_BOARD: "/admin/board",
  ADMIN_ROLES: "/admin/roles",
} as const
